# Generated by Django 2.2.19 on 2022-01-30 09:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color',
                 colorfield.fields.ColorField(
                     blank=True, default='#FF0000',
                     image_field=None,
                     max_length=18,
                     null=True,
                     samples=None)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
