# Generated by Django 2.2.19 on 2022-01-31 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('ingredient',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='recipes.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(max_length=200,
                                  verbose_name='Название')),
                ('image',
                 models.ImageField(
                     blank=True,
                     null=True,
                     upload_to='recipes/images/',
                     verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Рецепт')),
                ('cooking_time',
                 models.PositiveIntegerField(
                     verbose_name='Время приготовления')),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='recipes',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Автор')),
                ('ingredients',
                 models.ManyToManyField(
                     blank=True,
                     null=True,
                     related_name='recipes',
                     through='recipes.IngredientRecipe',
                     to='recipes.Ingredient',
                     verbose_name='Ингредиенты')),
            ],
        ),
        migrations.CreateModel(
            name='TagRecipe',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('recipe',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='recipes.Recipe')),
                ('tag',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to='recipes.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(
                related_name='recipes',
                through='recipes.TagRecipe',
                to='recipes.Tag',
                verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.Recipe'),
        ),
    ]
