# Generated by Django 2.2.19 on 2022-01-31 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20220131_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[(
                 'id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')
                ),
                ('recipe',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='shopping_cart',
                     to='recipes.Recipe',
                     verbose_name='Рецепт')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='shopping_cart',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True, serialize=False,
                     verbose_name='ID')),
                ('recipe',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='favorites',
                     to='recipes.Recipe',
                     verbose_name='Рецепт')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='favorites',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Пользователь')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'),
                                               name='unique_shoping_cart'),
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'),
                                               name='unique_favorites'),
        ),
    ]
