# Generated by Django 2.2.19 on 2022-01-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220131_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='recipes',
                through='recipes.IngredientRecipe',
                to='recipes.Ingredient',
                verbose_name='Ингредиенты'),
        ),
    ]
