# Generated by Django 2.2.19 on 2022-02-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220131_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_of_Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False,
                 verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ingredient',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='amount', to='recipes.Ingredient')),
            ],
        ),
    ]
