# Generated by Django 2.2.19 on 2022-02-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_number_of_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_of_ingredients',
            name='recipe',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='amount',
                to='recipes.Recipe'),
            preserve_default=False,
        ),
    ]
