# Generated by Django 2.2.19 on 2022-02-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_number_of_ingredients_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Number_of_Ingredients',
            new_name='NumberOfIngredients',
        ),
    ]
