# Generated by Django 2.2.19 on 2022-01-27 15:58

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('last_login',
                 models.DateTimeField(blank=True,
                                      null=True,
                                      verbose_name='last login')),
                ('is_superuser',
                 models.BooleanField(
                     default=False,
                     help_text='Designates...',
                     verbose_name='superuser status')),
                ('is_active',
                 models.BooleanField(default=True,
                                     help_text='Designates.',
                                     verbose_name='active')),
                ('date_joined',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      verbose_name='date joined')),
                ('email',
                 models.EmailField(max_length=254,
                                   unique=True)),
                ('username',
                 models.CharField(max_length=150,
                                  unique=True)),
                ('password',
                 models.CharField(max_length=150)),
                ('first_name',
                 models.CharField(max_length=150)),
                ('last_name',
                 models.CharField(max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups',
                 models.ManyToManyField(blank=True,
                                        help_text='The groups.',
                                        related_name='user_set',
                                        related_query_name='user',
                                        to='auth.Group',
                                        verbose_name='groups')),
                ('user_permissions',
                 models.ManyToManyField(blank=True,
                                        help_text='Specific.',
                                        related_name='user_set',
                                        related_query_name='user',
                                        to='auth.Permission',
                                        verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
